apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datastax-dse.fullname" . }}-cass-configuration
  labels:
    app: {{ template "datastax-dse.name" . }}
    chart: {{ template "datastax-dse.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
{{ $dir := include "datastax-dse.filevg-cass" . }}
{{- (.Files.Glob $dir).AsConfig | nindent 2 }}
