apiVersion: v1
kind: Service
metadata:
  name: {{ include "datastax-dse.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "datastax-dse.name" . }}
    helm.sh/chart: {{ include "datastax-dse.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9042 
      protocol: TCP
      name: cql
  selector:
    app.kubernetes.io/name: {{ include "datastax-dse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
